### ISSUE TITLE
Attempt to get the angular app live

### ISSUE THREAD

**Issue by bmitchinson** [Haiti-Distributed-Healthcare-System/senior-design-fa19-sp20#6]
Would also be useful for understanding the requirements of fields for patient data entry on site.

This is to understand what would be valuable to extract from the angular app, maybe height weight (growth) charts, who knows what else.

**Comment by abpwrs** [comment]
```
npm install
ng serve
```
The angular app works, but we are currently unable to connect it to the database.

**Comment by bmitchinson** [comment]
@abpwrs we needed to connect it to the database in order to view some of the forms right? Should we just close this ticket with the knowledge that if we ever really need it, we can try to hook it up?

**Comment by abpwrs** [comment]
Is this still worthwhile or can this issue be closed now?

**Comment by bmitchinson** [comment]
I think we can close
