### ISSUE TITLE
Begin a Figma design / lo - fi sketches for PWA design

### ISSUE THREAD

**Issue by bmitchinson** [Haiti-Distributed-Healthcare-System/senior-design-fa19-sp20#7]

**Comment by abpwrs** [comment]
Any preference/thoughts on figma vs sketch?

**Comment by bmitchinson** [comment]
Would love to learn sketch since i'm already familiar with figma but, sketch isn't free and isn't cross platform. 

EDIT: to my knowledge and after a quick google anyway

**Comment by abpwrs** [comment]
This has been done. We are using a shared Figma workspace.
